[["WW_",0,"World",1],
     ["WW_EUR","WW_","Europe"],
     ["EUR_GAS", "WW_EUR", "G.A.S"],
	["AL" , "WW_EUR" , "Albania"],
	//["AD" , "WW_EUR" , "Andorra"],
	["AT" , "EUR_GAS" , "Austria"],
	["BY" , "WW_EUR" , "Belarus"],
	["BE" , "WW_EUR" , "Belgium"],
	["BA" , "WW_EUR" , "Bosnia and Herzegovina"],
	["BG" , "WW_EUR" , "Bulgaria"],
	["HR" , "WW_EUR" , "Croatia"],
	["CY" , "WW_EUR" , "Cyprus"],
	["CZ" , "WW_EUR" , "Czech Republic"],
	["DK" , "WW_EUR" , "Denmark"],
	//["DD" , "WW_EUR" , "East Germany"],
	["EE" , "WW_EUR" , "Estonia"],
	//["FO" , "WW_EUR" , "Faroe Islands"],
	["FI" , "WW_EUR" , "Finland"],
	["FR" , "WW_EUR" , "France"],
	["DE" , "EUR_GAS" , "Germany"],
	//["GI" , "WW_EUR" , "Gibraltar"],
	["GR" , "WW_EUR" , "Greece"],
	//["GG" , "WW_EUR" , "Guernsey"],
	["HU" , "WW_EUR" , "Hungary"],
	["IS" , "WW_EUR" , "Iceland"],
	["IE" , "WW_EUR" , "Ireland"],
	//["IM" , "WW_EUR" , "Isle of Man"],
	["IT" , "WW_EUR" , "Italy"],
	//["JE" , "WW_EUR" , "Jersey"],
	["LV" , "WW_EUR" , "Latvia"],
	//["LI" , "WW_EUR" , "Liechtenstein"],
	["LT" , "WW_EUR" , "Lithuania"],
	["LU" , "WW_EUR" , "Luxembourg"],
	["MK" , "WW_EUR" , "Macedonia"],
	//["MT" , "WW_EUR" , "Malta"],
	//["FX" , "WW_EUR" , "Metropolitan France"],
	["MD" , "WW_EUR" , "Moldova"],
	//["MC" , "WW_EUR" , "Monaco"],
	["ME" , "WW_EUR" , "Montenegro"],
	["NL" , "WW_EUR" , "Netherlands"],
	["NO" , "WW_EUR" , "Norway"],
	["PL" , "WW_EUR" , "Poland"],
	["PT" , "WW_EUR" , "Portugal"],
	["RO" , "WW_EUR" , "Romania"],
	["RU" , "WW_EUR" , "Russia"],
	//["SM" , "WW_EUR" , "San Marino"],
	["RS" , "WW_EUR" , "Serbia"],
	//["CS" , "WW_EUR" , "Serbia and Montenegro"],
	["SK" , "WW_EUR" , "Slovakia"],
	["SI" , "WW_EUR" , "Slovenia"],
	["ES" , "WW_EUR" , "Spain"],
	//["SJ" , "WW_EUR" , "Svalbard and Jan Mayen"],
	["SE" , "WW_EUR" , "Sweden"],
	["CH" , "EUR_GAS" , "Switzerland"],
	["UA" , "WW_EUR" , "Ukraine"],
	//["SU" , "WW_EUR" , "Union of Soviet Socialist Republics"],
	["GB" , "WW_EUR" , "United Kingdom"],
	//["VA" , "WW_EUR" , "Vatican City"],
	//["AX" , "WW_EUR" , "Åland Islands"],
    ["WW_AMER","WW_","Americas"],
	//["AI" , "WW_AMER", "Anguilla"],
	//["AG" , "WW_AMER", "Antigua and Barbuda"],
	["AR" , "WW_AMER", "Argentina"],
	//["AW" , "WW_AMER", "Aruba"],
	["BS" , "WW_AMER", "Bahamas"],
	//["BB" , "WW_AMER", "Barbados"],
	["BZ" , "WW_AMER", "Belize"],
	//["BM" , "WW_AMER", "Bermuda"],
	["BO" , "WW_AMER", "Bolivia"],
	["BR" , "WW_AMER", "Brazil"],
	//["VG" , "WW_AMER", "British Virgin Islands"],
	["CA" , "WW_AMER", "Canada"],
	//["KY" , "WW_AMER", "Cayman Islands"],
	["CL" , "WW_AMER", "Chile"],
	["CO" , "WW_AMER", "Colombia"],
	["CR" , "WW_AMER", "Costa Rica"],
	["CU" , "WW_AMER", "Cuba"],
	//["DM" , "WW_AMER", "Dominica"],
	["DO" , "WW_AMER", "Dominican Republic"],
	["EC" , "WW_AMER", "Ecuador"],
	["SV" , "WW_AMER", "El Salvador"],
	["FK" , "WW_AMER", "Falkland Islands"],
	//["GF" , "WW_AMER", "French Guiana"],
	//["GL" , "WW_AMER", "Greenland"],
	//["GD" , "WW_AMER", "Grenada"],
	//["GP" , "WW_AMER", "Guadeloupe"],
	["GT" , "WW_AMER", "Guatemala"],
	["GY" , "WW_AMER", "Guyana"],
	["HT" , "WW_AMER", "Haiti"],
	["HN" , "WW_AMER", "Honduras"],
	["JM" , "WW_AMER", "Jamaica"],
	//["MQ" , "WW_AMER", "Martinique"],
	["MX" , "WW_AMER", "Mexico"],
	//["MS" , "WW_AMER", "Montserrat"],
	//["AN" , "WW_AMER", "Netherlands Antilles"],
	["NI" , "WW_AMER", "Nicaragua"],
	["PA" , "WW_AMER", "Panama"],
	["PY" , "WW_AMER", "Paraguay"],
	["PE" , "WW_AMER", "Peru"],
	["PR" , "WW_AMER", "Puerto Rico"],
	//["BL" , "WW_AMER", "Saint Barthélemy"],
	//["KN" , "WW_AMER", "Saint Kitts and Nevis"],
	//["LC" , "WW_AMER", "Saint Lucia"],
	//["MF" , "WW_AMER", "Saint Martin"],
	//["PM" , "WW_AMER", "Saint Pierre and Miquelon"],
	//["VC" , "WW_AMER", "Saint Vincent and the Grenadines"],
	["SR" , "WW_AMER", "Suriname"],
	["TT" , "WW_AMER", "Trinidad and Tobago"],
	//["TC" , "WW_AMER", "Turks and Caicos Islands"],
	//["VI" , "WW_AMER", "U.S. Virgin Islands"],
	["US" , "WW_AMER", "United States"],
	["UY" , "WW_AMER", "Uruguay"],
	["VE" , "WW_AMER", "Venezuela"],
    ["WW_ASIA","WW_","Asia"],
	["AF" , "WW_ASIA" , "Afghanistan"],
	["AM" , "WW_ASIA" , "Armenia"],
	["AZ" , "WW_ASIA" , "Azerbaijan"],
	//["BH" , "WW_ASIA" , "Bahrain"],
	["BD" , "WW_ASIA" , "Bangladesh"],
	["BT" , "WW_ASIA" , "Bhutan"],
	["BN" , "WW_ASIA" , "Brunei"],
	["KH" , "WW_ASIA" , "Cambodia"],
	["CN" , "WW_ASIA" , "China"],
	["GE" , "WW_ASIA" , "Georgia"],
	//["HK" , "WW_ASIA" , "Hong Kong SAR China"],
	["IN" , "WW_ASIA" , "India"],
	["ID" , "WW_ASIA" , "Indonesia"],
	["IR" , "WW_ASIA" , "Iran"],
	["IQ" , "WW_ASIA" , "Iraq"],
	["IL" , "WW_ASIA" , "Israel"],
	["JP" , "WW_ASIA" , "Japan"],
	["JO" , "WW_ASIA" , "Jordan"],
	["KZ" , "WW_ASIA" , "Kazakhstan"],
	["KW" , "WW_ASIA" , "Kuwait"],
	["KG" , "WW_ASIA" , "Kyrgyzstan"],
	["LA" , "WW_ASIA" , "Laos"],
	["LB" , "WW_ASIA" , "Lebanon"],
	//["MO" , "WW_ASIA" , "Macau SAR China"],
	["MY" , "WW_ASIA" , "Malaysia"],
	//["MV" , "WW_ASIA" , "Maldives"],
	["MN" , "WW_ASIA" , "Mongolia"],
	["MM" , "WW_ASIA" , "Myanmar [Burma]"],
	["NP" , "WW_ASIA" , "Nepal"],
	//["NT" , "WW_ASIA" , "Neutral Zone"],
	["KP" , "WW_ASIA" , "North Korea"],
	["OM" , "WW_ASIA" , "Oman"],
	["PK" , "WW_ASIA" , "Pakistan"],
	["PS" , "WW_ASIA" , "Palestinian Territories"],
	//["YD" , "WW_ASIA" , "People's Democratic Republic of Yemen"],
	["PH" , "WW_ASIA" , "Philippines"],
	["QA" , "WW_ASIA" , "Qatar"],
	["SA" , "WW_ASIA" , "Saudi Arabia"],
	//["SG" , "WW_ASIA" , "Singapore"],
	["KR" , "WW_ASIA" , "South Korea"],
	["LK" , "WW_ASIA" , "Sri Lanka"],
	["SY" , "WW_ASIA" , "Syria"],
	["TW" , "WW_ASIA" , "Taiwan"],
	["TJ" , "WW_ASIA" , "Tajikistan"],
	["TH" , "WW_ASIA" , "Thailand"],
	["TL" , "WW_ASIA" , "Timor-Leste"],
	["TR" , "WW_ASIA" , "Turkey"],
	["TM" , "WW_ASIA" , "Turkmenistan"],
	["AE" , "WW_ASIA" , "United Arab Emirates"],
	["UZ" , "WW_ASIA" , "Uzbekistan"],
	["VN" , "WW_ASIA" , "Vietnam"],
	["YE" , "WW_ASIA" , "Yemen"],
    ["WW_OCE","WW_","Oceania"],
	//["AS" , "WW_OCE" , "American Samoa"],
	//["AQ" , "WW_OCE" , "Antarctica"],
	["AU" , "WW_OCE" , "Australia"],
	//["BV" , "WW_OCE" , "Bouvet Island"],
	//["IO" , "WW_OCE" , "British Indian Ocean Territory"],
	//["CX" , "WW_OCE" , "Christmas Island"],
	//["CC" , "WW_OCE" , "Cocos [Keeling] Islands"],
	//["CK" , "WW_OCE" , "Cook Islands"],
	["FJ" , "WW_OCE" , "Fiji"],
	//["PF" , "WW_OCE" , "French Polynesia"],
	["TF" , "WW_OCE" , "French Southern Territories"],
	//["GU" , "WW_OCE" , "Guam"],
	//["HM" , "WW_OCE" , "Heard Island and McDonald Islands"],
	//["KI" , "WW_OCE" , "Kiribati"],
	//["MH" , "WW_OCE" , "Marshall Islands"],
	//["FM" , "WW_OCE" , "Micronesia"],
	//["NR" , "WW_OCE" , "Nauru"],
	["NC" , "WW_OCE" , "New Caledonia"],
	["NZ" , "WW_OCE" , "New Zealand"],
	//["NU" , "WW_OCE" , "Niue"],
	//["NF" , "WW_OCE" , "Norfolk Island"],
	//["MP" , "WW_OCE" , "Northern Mariana Islands"],
	//["PW" , "WW_OCE" , "Palau"],
	["PG" , "WW_OCE" , "Papua New Guinea"],
	//["PN" , "WW_OCE" , "Pitcairn Islands"],
	//["WS" , "WW_OCE" , "Samoa"],
	["SB" , "WW_OCE" , "Solomon Islands"],
	//["GS" , "WW_OCE" , "South Georgia and the South Sandwich Islands"],
	//["TK" , "WW_OCE" , "Tokelau"],
	//["TO" , "WW_OCE" , "Tonga"],
	//["TV" , "WW_OCE" , "Tuvalu"],
	//["UM" , "WW_OCE" , "U.S. Minor Outlying Islands"],
	["VU" , "WW_OCE" , "Vanuatu"],
	//["WF" , "WW_OCE" , "Wallis and Futuna"],
            ["WW_AFR","WW_","Africa"],
	["DZ" , "WW_AFR", "Algeria"],
	["AO" , "WW_AFR", "Angola"],
	["BJ" , "WW_AFR", "Benin"],
	["BW" , "WW_AFR", "Botswana"],
	["BF" , "WW_AFR", "Burkina Faso"],
	["BI" , "WW_AFR", "Burundi"],
	["CM" , "WW_AFR", "Cameroon"],
	//["CV" , "WW_AFR", "Cape Verde"],
	["CF" , "WW_AFR", "Central African Republic"],
	["TD" , "WW_AFR", "Chad"],
	//["KM" , "WW_AFR", "Comoros"],
	["CG" , "WW_AFR", "Congo - Brazzaville"],
	["CD" , "WW_AFR", "Congo - Kinshasa"],
	["CI" , "WW_AFR", "Côte d’Ivoire"],
	["DJ" , "WW_AFR", "Djibouti"],
	["EG" , "WW_AFR", "Egypt"],
	["GQ" , "WW_AFR", "Equatorial Guinea"],
	["ER" , "WW_AFR", "Eritrea"],
	["ET" , "WW_AFR", "Ethiopia"],
	["GA" , "WW_AFR", "Gabon"],
	["GM" , "WW_AFR", "Gambia"],
	["GH" , "WW_AFR", "Ghana"],
	["GN" , "WW_AFR", "Guinea"],
	["GW" , "WW_AFR", "Guinea-Bissau"],
	["KE" , "WW_AFR", "Kenya"],
	["LS" , "WW_AFR", "Lesotho"],
	["LR" , "WW_AFR", "Liberia"],
	["LY" , "WW_AFR", "Libya"],
	["MG" , "WW_AFR", "Madagascar"],
	["MW" , "WW_AFR", "Malawi"],
	["ML" , "WW_AFR", "Mali"],
	["MR" , "WW_AFR", "Mauritania"],
	//["MU" , "WW_AFR", "Mauritius"],
	//["YT" , "WW_AFR", "Mayotte"],
	["MA" , "WW_AFR", "Morocco"],
	["MZ" , "WW_AFR", "Mozambique"],
	["NA" , "WW_AFR", "Namibia"],
	["NE" , "WW_AFR", "Niger"],
	["NG" , "WW_AFR", "Nigeria"],
	["RW" , "WW_AFR", "Rwanda"],
	//["RE" , "WW_AFR", "Réunion"],
	//["SH" , "WW_AFR", "Saint Helena"],
	["SN" , "WW_AFR", "Senegal"],
	//["SC" , "WW_AFR", "Seychelles"],
	["SL" , "WW_AFR", "Sierra Leone"],
	["SO" , "WW_AFR", "Somalia"],
	["ZA" , "WW_AFR", "South Africa"],
	["SD" , "WW_AFR", "Sudan"],
	["SZ" , "WW_AFR", "Swaziland"],
	//["ST" , "WW_AFR", "São Tomé and Príncipe"],
	["TZ" , "WW_AFR", "Tanzania"],
	["TG" , "WW_AFR", "Togo"],
	["TN" , "WW_AFR", "Tunisia"],
	["UG" , "WW_AFR", "Uganda"],
	//["EH" , "WW_AFR", "Western Sahara"],
	["ZM" , "WW_AFR", "Zambia"],
	["ZW" , "WW_AFR", "Zimbabwe"]
        ]
